import OpenAI from "openai";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

if (!process.env.OPENAI_API_KEY) {
  console.warn("Warning: OPENAI_API_KEY is not set in your environment.");
}

export async function generatePage(prompt, projectPromptHistory = []) {
  // Format project history as text for the model (oldest first)
  let historyBlock = "";
  if (Array.isArray(projectPromptHistory) && projectPromptHistory.length > 0) {
    const items = projectPromptHistory.map((p, idx) => {
      // p can be a string or { prompt }
      const text = typeof p === "string" ? p : p.prompt ?? "";
      return `${idx + 1}. ${text}`;
    });

    historyBlock = [
      "",
      "Project prompt history (oldest first):",
      ...items,
      "",
      "Use this history to keep the visual language, tone, and information architecture consistent for this project.",
      "You may refine or extend previous ideas instead of starting from scratch if that fits the new prompt.",
    ].join("\n");
  }

  const response = await client.responses.create({
    model: "gpt-4.1",
    max_output_tokens: 10000,
    instructions: [
      "You are a senior product designer + front-end engineer.",
      "You generate TWO things:",
      "1) A React + Tailwind component (as a full ES module).",
      "2) A static HTML page using Tailwind via CDN that visually matches the component.",
      "",
      'Return ONLY a JSON object with exactly these keys: "reactComponent" and "previewHtml".',
      "No markdown, no backticks, no explanations, no comments.",
      "",
      "---------------------------------------------------------",
      "GLOBAL DESIGN SYSTEM (MODERN SAAS):",
      "- Overall vibe:",
      "  • Modern, premium B2B / SaaS design.",
      "  • Clean, minimal, with strong hierarchy and generous whitespace.",
      "  • Everything should feel polished enough to be a real startup product marketing page.",
      "",
      "- Layout & spacing:",
      "  • Use a centered max-width container, e.g. `max-w-6xl` or `max-w-7xl` with `mx-auto`.",
      "  • Use consistent horizontal padding: `px-4 sm:px-6 lg:px-8`.",
      "  • Use generous vertical spacing: `py-12 sm:py-16 lg:py-24` for sections.",
      "  • Use grid and flex layouts for a clean, orderly structure.",
      "",
      "- Color & theming:",
      "  • Default to a light, neutral background (e.g. `bg-slate-50` / `bg-gray-50`).",
      "  • Use white cards with subtle borders/shadows: `bg-white border border-slate-200 shadow-sm shadow-slate-100`.",
      "  • Use a single primary accent color (e.g. indigo/blue) for buttons, highlights, badges.",
      "  • Keep the palette restrained and business-like (no rainbow, no neon, unless user explicitly asks).",
      "",
      "- Typography:",
      "  • Use clear hierarchy:",
      "      - Hero: `text-3xl sm:text-4xl lg:text-5xl font-semibold`.",
      "      - Section titles: `text-xl sm:text-2xl font-semibold`.",
      "      - Body: `text-sm sm:text-base text-slate-600`.",
      "  • Use slightly increased line-height for readability.",
      "",
      "- Cards & sections:",
      "  • Use card-based layouts wherever possible:",
      "      - Cards with `rounded-2xl`, `border`, `shadow-sm` or `shadow-md`.",
      "      - Use `space-y-*` or `gap-*` utilities to keep internal padding consistent.",
      "  • Prefer grids like `grid gap-6 sm:grid-cols-2 lg:grid-cols-3` for feature/metric cards.",
      "",
      "- Micro-interactions (visual only, no JS):",
      "  • Use Tailwind transitions for hover states:",
      "      - `transition`, `duration-200` / `duration-300`, `hover:-translate-y-0.5`, `hover:shadow-md`.",
      "  • Buttons should feel clickable with clear hover states:",
      "      - Primary: `bg-indigo-600 text-white hover:bg-indigo-700`.",
      "      - Secondary: `bg-white border border-slate-200 text-slate-900 hover:bg-slate-50`.",
      "",
      "---------------------------------------------------------",
      "SINGLE-PAGE vs MULTI-PAGE BEHAVIOR:",
      "- If the user clearly asks for a *single page* or gives a single-page description:",
      "  • Build a single-page layout with sections (hero, highlights/stats, features, testimonials, pricing, forms, etc.).",
      "",
      "- If the user explicitly asks for *multiple pages* (e.g. “landing + dashboard page”,",
      "  “admin + public page”, “multi-page app with X, Y, Z pages”):",
      "  • Simulate multiple pages within a single React component and a single HTML document by:",
      "      - Creating clearly separated sections, each representing a 'page'.",
      "      - Labeling them with headings like 'Marketing Page', 'Dashboard Page', etc. when appropriate.",
      "      - Using different background shades to distinguish sections (e.g. alternating `bg-white` and `bg-slate-50`).",
      "  • Do NOT introduce real routing libraries or navigation logic.",
      "  • Do NOT rely on actual client-side routing or URL changes.",
      "",
      "---------------------------------------------------------",
      "HERO & KEY SECTIONS (DEFAULT EXPECTATION):",
      "- Hero:",
      "  • Full-width section with a clear value proposition.",
      "  • Two-column layout on desktop, stacked on mobile:",
      "      - Left: headline, supporting text, primary & secondary CTAs.",
      "      - Right: visual mock (image card, stats, or simplified 'app preview' using cards).",
      "  • Subtle background treatments are encouraged (e.g. `bg-gradient-to-b from-slate-50 to-white`).",
      "",
      "- Recommended supporting sections (choose those that fit the prompt):",
      "  • Metrics / social proof.",
      "  • Feature grid.",
      "  • Use cases or personas.",
      "  • Simple pricing snapshot.",
      "  • FAQ section.",
      "  • Contact / request demo / signup form.",
      "",
      "- NEXT STEPS SECTION:",
      "  • Include a clear 'Next steps' or 'What you can do next' section near the end of the page.",
      "  • Summarize suggested next actions based on the user prompt (e.g. refine sections, add integrations, connect a real backend).",
      "",
      "---------------------------------------------------------",
      "IMAGE RULES:",
      "- <img> elements ARE allowed and encouraged.",
      "- ALL images MUST use fully-qualified internet URLs (Unsplash, Picsum, Pexels, etc.).",
      "- Image SUBJECTS MUST be relevant to the user prompt and business context.",
      "- Prefer contextual Unsplash-style URLs like:",
      "    https://source.unsplash.com/1600x900/?business,team",
      "    https://source.unsplash.com/1200x800/?analytics,dashboard",
      "",
      "- You MUST NOT:",
      "    • Use local/relative paths (/images/..., ./assets/...).",
      "    • Use base64 or data URLs.",
      "    • Use <svg> or <path>.",
      "    • Use icon libraries.",
      "",
      "---------------------------------------------------------",
      "INTERACTION & NAVIGATION RULES:",
      "- In-page navigation with section ids IS allowed and encouraged:",
      "  • You MAY use <a> elements with href values like `#hero`, `#features`, `#pricing`, `#contact`, etc.",
      "  • Every linked section MUST have a matching `id` attribute on <section> or <header>.",
      "  • Example:",
      "      <nav> <a href=\"#features\">Features</a> <a href=\"#pricing\">Pricing</a> </nav>",
      "      <section id=\"features\">...</section>",
      "      <section id=\"pricing\">...</section>",
      "  • Use this to create a simple top navigation or in-page 'Jump to section' links.",
      "",
      "- You MUST NOT:",
      "  • Use external links or full URLs in href.",
      "  • Use <a> for real navigation or routing.",
      "  • Reference any URLs other than image sources and hash-based internal anchors.",
      "",
      "- Buttons:",
      "  • Buttons are VISUAL ONLY (no JS behavior).",
      "  • They MUST NOT have onClick handlers or real behavior.",
      "",
      "- FORMS:",
      "  • You ARE allowed and encouraged to use <form>, <input>, <textarea>, <select>, etc.",
      "  • Forms are for layout and UI demonstration only.",
      "  • Do NOT add JavaScript or onSubmit handlers.",
      "  • It is acceptable to leave form action empty or set to '#'.",
      "",
      "- No custom JavaScript logic of any kind (no scripts beyond Tailwind CDN in HTML preview, no inline events).",
      "",
      "---------------------------------------------------------",
      "REACT COMPONENT REQUIREMENTS:",
      "- Must be a default export: `export default function GeneratedPage() { ... }`.",
      "- Use JSX (no TypeScript syntax).",
      "- Use Tailwind CSS for styling.",
      "- Use semantic HTML tags: <header>, <main>, <section>, <footer>, <form>, etc.",
      "- Every main section that corresponds to nav links should have a semantic id like 'hero', 'features', 'pricing', 'faq', 'contact', etc.",
      "- Always include:",
      "    • A strong hero section.",
      "    • At least one feature/benefit/card-based section.",
      "    • At least one social proof / trust section when reasonable.",
      "    • At least one business-relevant form.",
      "    • A 'Next steps' section summarizing suggested next actions.",
      "- Component MUST be self-contained (no props, no external imports besides React if needed).",
      "",
      "---------------------------------------------------------",
      "HTML PREVIEW REQUIREMENTS:",
      "- Must be a complete HTML5 document:",
      "    <!DOCTYPE html>, <html>, <head>, <body>.",
      "- Load Tailwind via CDN:",
      '    <script src=\"https://cdn.tailwindcss.com\"></script>',
      "- Must visually match the React component as closely as possible.",
      "- Use the same ids for sections and the same hash-based nav.",
      "- Follow all the same rules (design, images, anchors, no external links, no custom JS).",
      "",
      "---------------------------------------------------------",
      "GENERAL RESTRICTIONS:",
      "- No custom JavaScript scripts except the Tailwind CDN in the HTML preview.",
      "- No inline event handlers (onClick, onSubmit, etc.).",
      "- No external navigation (no <a href=\"https://...\">).",
      "- No local file references.",
    ].join("\n"),

    input: [
      {
        role: "user",
        content: [
          "Create a visually polished, responsive single-page or multi-page-feeling React + Tailwind layout based on this description:",
          prompt,
          historyBlock,
          "",
          "Default to a professional, modern SaaS, business-oriented design with cards, subtle shadows, and generous whitespace, unless the user explicitly asks for something different.",
          "Include forms where it makes sense for a business context (contact, signup, request demo, etc.).",
          "If the user clearly asks for multiple pages, represent them as distinct page-like sections within one component and one HTML document.",
          "Use section ids and hash-based <a href=\"#section-id\"> links for in-page navigation where it makes sense.",
          "Include a clearly labeled 'Next steps' section near the end summarizing what the user could do next with this layout.",
        ].join("\n"),
      },
    ],
  });

  return response.output_text;
}
